APP_PORT=3000
DATABASE_URL=postgresql://remnawave:${POSTGRES_PASSWORD}@postgres:5432/remnawave
JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
JWT_API_TOKENS_SECRET=${JWT_API_TOKENS_SECRET}
REDIS_URL=redis://redis:6379
SUB_PUBLIC_DOMAIN=https://${PANEL_DOMAIN}
