APP_PORT=3000
METRICS_PORT=3001
API_INSTANCES=1

DATABASE_URL=postgresql://remnawave:${POSTGRES_PASSWORD}@postgres:5432/remnawave
REDIS_HOST=redis
REDIS_PORT=6379

JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
JWT_API_TOKENS_SECRET=${JWT_API_TOKENS_SECRET}

IS_TELEGRAM_NOTIFICATIONS_ENABLED=false

PANEL_DOMAIN=${PANEL_DOMAIN}
FRONT_END_DOMAIN=*
SUB_PUBLIC_DOMAIN=${SUB_DOMAIN}

IS_DOCS_ENABLED=false

METRICS_USER=admin
METRICS_PASS=${METRICS_PASS}

WEBHOOK_ENABLED=false
