---
- name: Install sing-box
  ansible.builtin.import_tasks: install.yml
  tags: [install]

- name: Deploy client config
  ansible.builtin.import_tasks: config.yml
  tags: [config]

- name: Configure Docker proxy
  ansible.builtin.import_tasks: docker-proxy.yml
  when: singbox_docker_proxy
  tags: [docker-proxy]
