---
all:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=publickey"
    ansible_python_interpreter: /usr/bin/python3

  hosts:
    work-d-01:
      ansible_host: VPN_SERVER_IP_PLACEHOLDER
      ts_hostname: work-d-0
      ts_advertise_routes: "192.168.20.0/24,192.168.82.0/24"
    # Work VM
    work-d-01:
      ansible_host: 192.168.82.61
      ts_hostname: work-d-01.infra
      ts_advertise_routes: "192.168.20.0/24,192.168.82.0/24"
    work-d-01-ts:
      ansible_host: 192.168.82.61

    # Proxmox Cluster
    pve-work-l-01:
      ansible_host: 192.168.20.151
      ts_hostname: pve-work-l-01.infra
    pve-work-l-01-ts:
      ansible_host: 100.64.0.3
    pve-work-l-02:
      ansible_host: 192.168.20.152
      ts_hostname: pve-work-l-02.infra
    pve-work-l-02-ts:
      ansible_host: 100.64.0.5
    pve-work-l-03:
      ansible_host: 192.168.20.153
      ts_hostname: pve-work-l-03.infra
    pve-work-l-03-ts:
      ansible_host: 100.64.0.4

    # Local Proxmox
    pve-local-l-01:
      ansible_host: 10.0.1.4
      ts_hostname: pve-local-l-01.infra
      ts_advertise_routes: "10.0.1.0/24"
    pve-local-l-01-ts:
      ansible_host: 100.64.0.21

    # Local Backup
    backup-home-01:
      ansible_host: 10.0.1.67
      ts_hostname: backup-home-01.backup
    backup-home-01-ts:
      ansible_host: 10.0.1.67

  children:
    pve_work:
      vars:
        ansible_user: root
        ts_accept_routes: false
      hosts:
        pve-work-l-01:
        pve-work-l-02:
        pve-work-l-03:
    pve_work_ts:
      vars:
        ansible_user: root
      hosts:
        pve-work-l-01-ts:
        pve-work-l-02-ts:
        pve-work-l-03-ts:

    pve_local:
      vars:
        ansible_user: root
        ts_accept_routes: false
      hosts:
        pve-local-l-01:
    pve_local_ts:
      vars:
        ansible_user: root
      hosts:
        pve-local-l-01-ts:

    pve:
      children:
        pve_work:
        pve_local:
    pve_ts:
      children:
        pve_work_ts:
        pve_local_ts:

    # ===== VM =====
    # vm_local:
    #   vars:
    #     ansible_user: "{{ inventory_hostname }}"
    #   hosts:
    #
    # vm_local_ts:
    #   vars:
    #     ansible_user: "{{ inventory_hostname }}"
    #   hosts:
    vm_work:
      vars:
        ansible_user: cluster
      hosts:
        work-d-01:
    vm_work_ts:
      vars:
        ansible_user: cluster
      hosts:
        work-d-01-ts:

    # ===== BARE METAL =====
    # bare_metal:
    #   vars:
    #     ansible_user: "{{ inventory_hostname }}"
    #     ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=publickey,password -o PasswordAuthentication=yes"
    #   hosts:
    #     rpi-home-p-01:
    #       ansible_host: 10.0.1.12
    #       ts_hostname: rpi-home-p-01.infra

    # bare_metal_ts:
    #   vars:
    #     ansible_user: "{{ inventory_hostname }}"
    #     ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=publickey,password -o PasswordAuthentication=yes"
    #   hosts:
    #     rpi-home-p-01:
    #       ansible_host: 100.64.0.18
