---
services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: sing-box
    restart: unless-stopped
    volumes:
      - ../configs/sing-box:/etc/sing-box
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    cap_add:
      - NET_ADMIN
    command: run -c /etc/sing-box/config.json
