---
services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: sing-box
    restart: unless-stopped
    environment:
      ENABLE_DEPRECATED_LEGACY_DOMAIN_STRATEGY_OPTIONS: "true"
    volumes:
      - ./configs/sing-box:/etc/sing-box
    healthcheck:
      test: ["CMD", "sing-box", "check", "-c", "/etc/sing-box/config.json"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "443:443/tcp"
      - "2053:2053/tcp"
      - "2083:2083/tcp"
      - "64444:64444/tcp"
      - "2087:2087/tcp"
      - "8443:8443/udp"
      - "8444:8444/udp"
      - "8388:8388/tcp"
      - "8445:8445/tcp"
      - "8389:8389/tcp"
    cap_add:
      - NET_ADMIN
    command: run -c /etc/sing-box/config.json
