---
- name: Check Tailscale state
  ansible.builtin.command:
    cmd: tailscale status
  register: ts_state
  failed_when: false
  changed_when: false
  tags: [install, authorize, uninstall, reinstall]

- name: Uninstall
  ansible.builtin.import_tasks: uninstall.yml
  when: ts_state.rc == 0
  tags: [uninstall, reinstall]

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags: [install, reinstall]

- name: Authorize
  ansible.builtin.import_tasks: authorize.yml
  tags: [authorize, reinstall]
