---
- name: Disconnect from Tailscale
  ansible.builtin.command:
    cmd: tailscale down
  failed_when: false

- name: Stop and disable tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    state: stopped
    enabled: false
  failed_when: false

- name: Remove files and directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/systemd/system/tailscaled.service
    - /etc/default/tailscaled
    - /usr/bin/tailscale
    - /usr/sbin/tailscaled
    - /var/lib/tailscale
    - /var/cache/tailscale
  notify: reload systemd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
