name: "Deploy: sing-box"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to deploy (leave empty for latest)'
        default: ''
  push:
    branches: [master]
    paths:
      - infra/vpn-nl/**
      - clients/sing-box/lib/**
      - .github/workflows/deploy-singbox.yml
      - .github/workflows/_deploy-vpn.yml

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-vpn.yml
    with:
      runner: vds-vpn-nl-01
      environment: vds-vpn-nl-01
      server: vpn-nl
      ref: ${{ inputs.ref || '' }}
    secrets: inherit
