name: "Deploy: mesh-hel-01"
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - configs/mesh/hel-01/**
jobs:
  deploy:
    uses: ./.github/workflows/_deploy-mesh.yml
    with:
      server: hel-01
    secrets: inherit
